name: Publish to npm

on:
  push:
    branches:
      - master
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: |
          npm ci
          npm test
          git config user.email "brian@olore.net"
          git config user.name "$GITHUB_ACTOR"
          npm run release
          git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/olore/jaycue.git" HEAD:master --follow-tags
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} # auto available